# Generated by Django 3.0.4 on 2020-04-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200403_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='characteristics',
            field=models.ManyToManyField(to='main_app.Characteristic'),
        ),
    ]
